#!/bin/bash
#SBATCH --job-name=nll_ssst          # Job name
#SBATCH --output=job_%j.out           # Standard output and error log
#SBATCH --partition=serc                 # Partition (queue) name
#SBATCH --nodes=1                        # Number of nodes
#SBATCH --ntasks=1                       # Number of tasks (processes)
#SBATCH --cpus-per-task=4                # Number of CPU cores per task
#SBATCH --mem=32G                        # Memory per node
#SBATCH --time=06:00:00                  # Time limit hrs:min:sec


srun ./run_ssst_relocations.bash
