#!/usr/bin/bash
#SBATCH --job-name=nll
#SBATCH --output=%j.out
#SBATCH --error=%j.err
#SBATCH --time=2:00:00
#SBATCH -p serc
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16GB
rm model/*
rm time/*
rm loc/*
Vel2Grid ./nlloc_sample.in
srun Grid2Time ./nlloc_sample.in
srun Grid2Time ./nlloc_sample.in_S
srun NLLoc ./nlloc_sample.in
